blank_issues_enabled: false
  contact_links:
    - name: Documentation
      url: https://ultramap.io/docs
      about: Check out the documentation for guides and tutorials
    - name: Community Discussions
      url: https://github.com/ethendaniels0/ultramap-feedback/discussions
      about: Ask questions and discuss ideas with the community
